# Generated by Django 4.0.5 on 2022-06-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido Cliente')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo Cliente')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion Cliente')),
            ],
        ),
    ]
